---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - prettier
plugins:
  - import
  - jest
  - json
  - prettier
rules:
  import/extensions: [warn, {js: never}]
  import/no-extraneous-dependencies: 'off'
  import/no-named-as-default: 'off'
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  prettier/prettier:
    - error
    - {
      singleQuote: true,
      trailingComma: all,
      useTabs: true
    }
